<a href="https://colab.research.google.com/github/YYM89/MSSP607/blob/main/Copy_of_week4_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import pandas as pd
import numpy as np
if os.path.exists('/content/drive'):
    print("Drive mounted successfully")
file_path = '/content/drive/MyDrive/MSSP607/Data/parsed.csv'
df = pd.read_csv(file_path)
print("Data imported successfully!")

Drive mounted successfully
Data imported successfully!

In [ ]:
#95th percentile of earthquake magnitude in Japan using magType of 'mb'
japan_mb = df[(df['parsed_place'] == 'Japan') & (df['magType'] == 'mb')]
percentile_95_japan = japan_mb['mag'].quantile(0.95)
print(f"95th percentile of earthquake magnitude in Japan (magType 'mb'): {percentile_95_japan}")

95th percentile of earthquake magnitude in Japan (magType 'mb'): 4.9

In [ ]:
#the percentage of earthquakes in Indonesia that were coupled with tsunamis
indonesia_earthquakes = df[df['parsed_place'] == 'Indonesia']
tsunami_in_indonesia = indonesia_earthquakes['tsunami'].sum()
percentage_tsunami_indonesia = (tsunami_in_indonesia / len(indonesia_earthquakes)) * 100
print(f"b. Percentage of earthquakes in Indonesia coupled with tsunamis: {percentage_tsunami_indonesia:.2f}%")

b. Percentage of earthquakes in Indonesia coupled with tsunamis: 23.13%

In [ ]:
#summary statistics for earthquakes in Nevada
nevada_earthquakes = df[df['parsed_place'] == 'Nevada']
summary_stats = nevada_earthquakes['mag'].describe()
print("Summary statistics for earthquakes in Nevada:")
print(summary_stats)

Summary statistics for earthquakes in Nevada:
count    681.000000
mean       0.500073
std        0.696710
min       -0.500000
25%       -0.100000
50%        0.400000
75%        0.900000
max        2.900000
Name: mag, dtype: float64

In [ ]:
#summary statistics for earthquakes in Nevada
df[df.parsed_place.str.endswith('Nevada')].describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,681.000000,15.000000,681.000000,681.000000,1.00,681.000000,681.000000,681.000000,6.810000e+02,681.0,681.0,6.810000e+02
mean,2.440000,0.166199,2.400000,153.668120,0.500073,2.84,12.618209,0.151986,10.970631,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166228,4.626013,68.735302,0.696710,NaN,9.866963,0.084662,19.607150,5.965637e+08,0.0,0.0,6.010951e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.053000,1.000000,97.380000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.112000,1.000000,149.140000,0.400000,2.84,10.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.233000,1.000000,199.720000,0.900000,2.84,16.000000,0.187100,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

In [ ]:
df['ring_of_fire'] = ''
df.columns

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag',
       'magType', 'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources',
       'status', 'time', 'title', 'tsunami', 'type', 'types', 'tz', 'updated',
       'url', 'parsed_place', 'ring_of_fire'],
      dtype='object')

In [ ]:
df['ring_of_fire'] = df.parsed_place.str.contains(r'|'.join([
    'Bolivia', 'Chile', 'Ecuador', 'Peru', 'Costa Rica',
    'Guatemala', '^Mexico', 'Japan', 'Philippines', 'Indonesia',
    'New Zealand', 'Antarctic', 'Canada', 'Fiji',
    'Alaska', 'Washington', 'California', 'Russia',
    'Taiwan', 'Tonga', 'Kermadec Islands'
]))
df[['ring_of_fire', 'parsed_place']]

      ring_of_fire parsed_place
0             True   California
1             True   California
2             True   California
3             True   California
4             True   California
...            ...          ...
9327          True   California
9328          True   California
9329         False  Puerto Rico
9330          True   California
9331          True   California

[9332 rows x 2 columns]

In [ ]:
df[['ring_of_fire', 'parsed_place']]

      ring_of_fire parsed_place
0             True   California
1             True   California
2             True   California
3             True   California
4             True   California
...            ...          ...
9327          True   California
9328          True   California
9329         False  Puerto Rico
9330          True   California
9331          True   California

[9332 rows x 2 columns]

In [ ]:
#Calculate the total number of events in the dataframe
df.type.value_counts()

type
earthquake      9081
quarry blast      95
explosion         80
ice quake         72
other event        4
Name: count, dtype: int64

In [ ]:
#Filter the dataframe for earthquakes on the ring of fire and outside of the ring.
filtered_df = df[(df['ring_of_fire'] == True) & (df['type'] == 'earthquake')]
total_inside = df[(df['ring_of_fire'] == True) & (df['type'] == 'earthquake')].type.count()
total_outside = df[(df['ring_of_fire'] == False) & (df['type'] == 'earthquake')].type.count()
print('The total number of earthquakes in the Ring of Fire is: ', total_inside)
print('The total number of earthquakes outside the Ring of Fire is: ', total_outside)

The total number of earthquakes in the Ring of Fire is:  7004
The total number of earthquakes outside the Ring of Fire is:  2077

In [ ]:
df['ring_of_fire'].value_counts()

ring_of_fire
True     7188
False    2144
Name: count, dtype: int64

In [ ]:
df.loc[df.ring_of_fire, 'tsunami'].sum()

np.int64(45)